variables:
  PROJECT_NAME: esocial-jt
  REGISTRY_HOST: os311-registry.tjdft.jus.br
  REGISTRY_USER: builder
  IMAGE_NAME_STAGE: esocialapp-stage
  IMAGE_NAME_PRODUCTION: esocialapp-production
stages:
  - build
  - deploy

############################
### TEMPLATE PARA DEPLOY
############################
.template_deploy: &template_deploy
  image: kaniko-project/executor:debug
  stage: deploy
  script:
    - echo "${REGISTRY_HOST}/${IMAGE_NAME}/${SERVICE_NAME}:${IMAGE_TAG}"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY_HOST}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${SA_USER_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CONTEXT_DIR}"
      --dockerfile "${DOCKERFILE_DIR}"
      --build-arg "release='${CI_COMMIT_SHA}'"
      --destination "${REGISTRY_HOST}/${IMAGE_NAME}/${SERVICE_NAME}:${IMAGE_TAG}"
      --registry-mirror "nexuspull.tjdft.jus.br"

build_backend:
  image: adoptopenjdk/maven-openjdk8
  stage: build
  only:
    - tags
  script:
    - cd src/
    - mvn -B verify
  artifacts:
    when: on_success
    paths:
      - ${CI_PROJECT_DIR}/src/esocial-jt-service/target
    expire_in: 1 day

build_frontend:
  image: ${CI_TEMPLATE_REGISTRY_HOST}node:16-bullseye
  stage: build
  only:
    - tags
  script:
    - cd frontend/
    - yarn install --frozen-lockfile
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    when: on_success
    paths:
      - frontend/build
    expire_in: 1 day
  dependencies:
    - build_backend

#===============================================================
# Ambiente desenv oficial
#===============================================================
deploy_backend_desenv:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/src/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/src
    IMAGE_NAME: ${IMAGE_NAME_STAGE}
    SERVICE_NAME: esocial-jt-backend
    IMAGE_TAG: desenv
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_STAGE
  dependencies:
    - build_backend

deploy_frontend_desenv:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/frontend/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/frontend
    IMAGE_NAME: ${IMAGE_NAME_STAGE}
    SERVICE_NAME: esocial-jt-frontend
    IMAGE_TAG: desenv
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_STAGE
  dependencies:
    - build_backend
    - build_frontend

#===============================================================
# Ambiente desenv testes
#===============================================================
deploy_backend_desenv_teste:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^teste-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/src/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/src
    IMAGE_NAME: ${IMAGE_NAME_STAGE}
    SERVICE_NAME: esocial-jt-backend-teste
    IMAGE_TAG: desenv-teste
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_STAGE
  dependencies:
    - build_backend

deploy_frontend_desenv_teste:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^teste-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/frontend/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/frontend
    IMAGE_NAME: ${IMAGE_NAME_STAGE}
    SERVICE_NAME: esocial-jt-frontend-teste
    IMAGE_TAG: desenv-teste
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_STAGE
  dependencies:
    - build_backend
    - build_frontend

#===============================================================
# Ambiente produção
#===============================================================
deploy_backend_prod:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^production-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/src/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/src
    IMAGE_NAME: ${IMAGE_NAME_PRODUCTION}
    SERVICE_NAME: esocial-jt-backend
    IMAGE_TAG: production
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_PROD
  dependencies:
    - build_backend

deploy_frontend_prod:
  <<: *template_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^production-.*$/
  variables:
    DOCKERFILE_DIR: ${CI_PROJECT_DIR}/frontend/Dockerfile
    CONTEXT_DIR: ${CI_PROJECT_DIR}/frontend
    IMAGE_NAME: ${IMAGE_NAME_PRODUCTION}
    SERVICE_NAME: esocial-jt-frontend
    IMAGE_TAG: production
  before_script:
    - SA_USER_TOKEN=$SA_USER_TOKEN_PROD
  dependencies:
    - build_backend
    - build_frontend
