//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.02 at 02:45:01 PM BRT 
//


package br.jus.tst.esocial.esquemas.eventos.excproctrab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evtExcProcTrab">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}T_ideEvento_exclusao_proc_trab"/>
 *                   &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}T_ideEmpregador_exclusao"/>
 *                   &lt;element name="infoExclusao">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tpEvento">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="6"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="nrRecEvt" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrRecibo"/>
 *                             &lt;element name="ideProcTrab">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nrProcTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrProcTrab"/>
 *                                       &lt;element name="cpfTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_cpf" minOccurs="0"/>
 *                                       &lt;element name="perApurPgto" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_periodo_mensal" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Id" use="required" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_Id" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "evtExcProcTrab",
    "signature"
})
@XmlRootElement(name = "eSocial")
public class ESocial {

    @XmlElement(required = true)
    protected ESocial.EvtExcProcTrab evtExcProcTrab;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the evtExcProcTrab property.
     * 
     * @return
     *     possible object is
     *     {@link ESocial.EvtExcProcTrab }
     *     
     */
    public ESocial.EvtExcProcTrab getEvtExcProcTrab() {
        return evtExcProcTrab;
    }

    /**
     * Sets the value of the evtExcProcTrab property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESocial.EvtExcProcTrab }
     *     
     */
    public void setEvtExcProcTrab(ESocial.EvtExcProcTrab value) {
        this.evtExcProcTrab = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}T_ideEvento_exclusao_proc_trab"/>
     *         &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}T_ideEmpregador_exclusao"/>
     *         &lt;element name="infoExclusao">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tpEvento">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="6"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="nrRecEvt" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrRecibo"/>
     *                   &lt;element name="ideProcTrab">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="nrProcTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrProcTrab"/>
     *                             &lt;element name="cpfTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_cpf" minOccurs="0"/>
     *                             &lt;element name="perApurPgto" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_periodo_mensal" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Id" use="required" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_Id" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ideEvento",
        "ideEmpregador",
        "infoExclusao"
    })
    public static class EvtExcProcTrab {

        @XmlElement(required = true)
        protected TIdeEventoExclusaoProcTrab ideEvento;
        @XmlElement(required = true)
        protected TIdeEmpregadorExclusao ideEmpregador;
        @XmlElement(required = true)
        protected ESocial.EvtExcProcTrab.InfoExclusao infoExclusao;
        @XmlAttribute(name = "Id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String id;

        /**
         * Gets the value of the ideEvento property.
         * 
         * @return
         *     possible object is
         *     {@link TIdeEventoExclusaoProcTrab }
         *     
         */
        public TIdeEventoExclusaoProcTrab getIdeEvento() {
            return ideEvento;
        }

        /**
         * Sets the value of the ideEvento property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIdeEventoExclusaoProcTrab }
         *     
         */
        public void setIdeEvento(TIdeEventoExclusaoProcTrab value) {
            this.ideEvento = value;
        }

        /**
         * Gets the value of the ideEmpregador property.
         * 
         * @return
         *     possible object is
         *     {@link TIdeEmpregadorExclusao }
         *     
         */
        public TIdeEmpregadorExclusao getIdeEmpregador() {
            return ideEmpregador;
        }

        /**
         * Sets the value of the ideEmpregador property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIdeEmpregadorExclusao }
         *     
         */
        public void setIdeEmpregador(TIdeEmpregadorExclusao value) {
            this.ideEmpregador = value;
        }

        /**
         * Gets the value of the infoExclusao property.
         * 
         * @return
         *     possible object is
         *     {@link ESocial.EvtExcProcTrab.InfoExclusao }
         *     
         */
        public ESocial.EvtExcProcTrab.InfoExclusao getInfoExclusao() {
            return infoExclusao;
        }

        /**
         * Sets the value of the infoExclusao property.
         * 
         * @param value
         *     allowed object is
         *     {@link ESocial.EvtExcProcTrab.InfoExclusao }
         *     
         */
        public void setInfoExclusao(ESocial.EvtExcProcTrab.InfoExclusao value) {
            this.infoExclusao = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tpEvento">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="6"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="nrRecEvt" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrRecibo"/>
         *         &lt;element name="ideProcTrab">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="nrProcTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrProcTrab"/>
         *                   &lt;element name="cpfTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_cpf" minOccurs="0"/>
         *                   &lt;element name="perApurPgto" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_periodo_mensal" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tpEvento",
            "nrRecEvt",
            "ideProcTrab"
        })
        public static class InfoExclusao {

            @XmlElement(required = true)
            protected String tpEvento;
            @XmlElement(required = true)
            protected String nrRecEvt;
            @XmlElement(required = true)
            protected ESocial.EvtExcProcTrab.InfoExclusao.IdeProcTrab ideProcTrab;

            /**
             * Gets the value of the tpEvento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTpEvento() {
                return tpEvento;
            }

            /**
             * Sets the value of the tpEvento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTpEvento(String value) {
                this.tpEvento = value;
            }

            /**
             * Gets the value of the nrRecEvt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNrRecEvt() {
                return nrRecEvt;
            }

            /**
             * Sets the value of the nrRecEvt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNrRecEvt(String value) {
                this.nrRecEvt = value;
            }

            /**
             * Gets the value of the ideProcTrab property.
             * 
             * @return
             *     possible object is
             *     {@link ESocial.EvtExcProcTrab.InfoExclusao.IdeProcTrab }
             *     
             */
            public ESocial.EvtExcProcTrab.InfoExclusao.IdeProcTrab getIdeProcTrab() {
                return ideProcTrab;
            }

            /**
             * Sets the value of the ideProcTrab property.
             * 
             * @param value
             *     allowed object is
             *     {@link ESocial.EvtExcProcTrab.InfoExclusao.IdeProcTrab }
             *     
             */
            public void setIdeProcTrab(ESocial.EvtExcProcTrab.InfoExclusao.IdeProcTrab value) {
                this.ideProcTrab = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="nrProcTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_nrProcTrab"/>
             *         &lt;element name="cpfTrab" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_cpf" minOccurs="0"/>
             *         &lt;element name="perApurPgto" type="{http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00}TS_periodo_mensal" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nrProcTrab",
                "cpfTrab",
                "perApurPgto"
            })
            public static class IdeProcTrab {

                @XmlElement(required = true)
                protected String nrProcTrab;
                protected String cpfTrab;
                protected String perApurPgto;

                /**
                 * Gets the value of the nrProcTrab property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNrProcTrab() {
                    return nrProcTrab;
                }

                /**
                 * Sets the value of the nrProcTrab property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNrProcTrab(String value) {
                    this.nrProcTrab = value;
                }

                /**
                 * Gets the value of the cpfTrab property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCpfTrab() {
                    return cpfTrab;
                }

                /**
                 * Sets the value of the cpfTrab property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCpfTrab(String value) {
                    this.cpfTrab = value;
                }

                /**
                 * Gets the value of the perApurPgto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPerApurPgto() {
                    return perApurPgto;
                }

                /**
                 * Sets the value of the perApurPgto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPerApurPgto(String value) {
                    this.perApurPgto = value;
                }

            }

        }

    }

}
