//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.30 at 04:37:51 PM BRST 
//


package br.jus.tst.esocialjt.comunicacao.lote.eventos.consulta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="consultaLoteEventos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="protocoloEnvio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consultaLoteEventos"
})
@XmlRootElement(name = "eSocial")
public class ESocial {

    @XmlElement(required = true)
    protected ESocial.ConsultaLoteEventos consultaLoteEventos;

    /**
     * Gets the value of the consultaLoteEventos property.
     * 
     * @return
     *     possible object is
     *     {@link ESocial.ConsultaLoteEventos }
     *     
     */
    public ESocial.ConsultaLoteEventos getConsultaLoteEventos() {
        return consultaLoteEventos;
    }

    /**
     * Sets the value of the consultaLoteEventos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESocial.ConsultaLoteEventos }
     *     
     */
    public void setConsultaLoteEventos(ESocial.ConsultaLoteEventos value) {
        this.consultaLoteEventos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="protocoloEnvio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "protocoloEnvio"
    })
    public static class ConsultaLoteEventos {

        @XmlElement(required = true)
        protected String protocoloEnvio;

        /**
         * Gets the value of the protocoloEnvio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocoloEnvio() {
            return protocoloEnvio;
        }

        /**
         * Sets the value of the protocoloEnvio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocoloEnvio(String value) {
            this.protocoloEnvio = value;
        }

    }

}
