ALTER TABLE EST_OCORRENCIA ADD TXT_CPF VARCHAR(11) NULL;
ALTER TABLE EST_OCORRENCIA ADD TXT_MATRICULA VARCHAR(30) NULL;
create index EST_OCORRENCIA_TXT_CPF on EST_OCORRENCIA (TXT_CPF);
create index EST_OCORRENCIA_TXT_MATRICULA on EST_OCORRENCIA (TXT_MATRICULA);
