ALTER TABLE EST_OCORRENCIA ADD TXT_PER_APURACAO VARCHAR(7) NULL;
ALTER TABLE EST_OCORRENCIA ADD COD_OCORRENCIA_EXCLUSAO INTEGER NULL;
ALTER TABLE EST_OCORRENCIA ADD COD_OCORRENCIA_RETIFICACAO INTEGER NULL;

CREATE INDEX EST_OCORRENCIA_TXT_PER_APURACAO ON EST_OCORRENCIA (TXT_PER_APURACAO);

ALTER TABLE EST_OCORRENCIA ADD CONSTRAINT EST_OCORRENCIA_EXCLUSAO_FK FOREIGN KEY (COD_OCORRENCIA_EXCLUSAO) REFERENCES EST_OCORRENCIA (COD_OCORRENCIA);
ALTER TABLE EST_OCORRENCIA ADD CONSTRAINT EST_OCORRENCIA_RETIFICACAO_FK FOREIGN KEY (COD_OCORRENCIA_RETIFICACAO) REFERENCES EST_OCORRENCIA (COD_OCORRENCIA);

