//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 02:26:29 PM BRST 
//


package br.jus.tst.esocial.esquemas.eventos.cdbenprrp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evtCdBenPrRP">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TIdeEveTrab"/>
 *                   &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TEmprPJ"/>
 *                   &lt;element name="ideBenef">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cpfBenef">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="\d{11}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="nmBenefic">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="2"/>
 *                                   &lt;maxLength value="70"/>
 *                                   &lt;whiteSpace value="preserve"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="dadosBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBenef"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="infoBeneficio">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tpPlanRP">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                                   &lt;pattern value="\d"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="iniBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
 *                             &lt;element name="altBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
 *                             &lt;element name="fimBeneficio" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tpBenef">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                                             &lt;pattern value="\d{1,2}"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="nrBenefic">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="2"/>
 *                                             &lt;maxLength value="20"/>
 *                                             &lt;whiteSpace value="preserve"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="dtFimBenef">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="mtvFim">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                                             &lt;pattern value="\d{1,2}"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "evtCdBenPrRP",
    "signature"
})
@XmlRootElement(name = "eSocial", namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
public class ESocial {

    @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
    protected ESocial.EvtCdBenPrRP evtCdBenPrRP;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the evtCdBenPrRP property.
     * 
     * @return
     *     possible object is
     *     {@link ESocial.EvtCdBenPrRP }
     *     
     */
    public ESocial.EvtCdBenPrRP getEvtCdBenPrRP() {
        return evtCdBenPrRP;
    }

    /**
     * Sets the value of the evtCdBenPrRP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESocial.EvtCdBenPrRP }
     *     
     */
    public void setEvtCdBenPrRP(ESocial.EvtCdBenPrRP value) {
        this.evtCdBenPrRP = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TIdeEveTrab"/>
     *         &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TEmprPJ"/>
     *         &lt;element name="ideBenef">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cpfBenef">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="\d{11}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="nmBenefic">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="2"/>
     *                         &lt;maxLength value="70"/>
     *                         &lt;whiteSpace value="preserve"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="dadosBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBenef"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="infoBeneficio">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tpPlanRP">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *                         &lt;pattern value="\d"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="iniBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
     *                   &lt;element name="altBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
     *                   &lt;element name="fimBeneficio" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="tpBenef">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *                                   &lt;pattern value="\d{1,2}"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="nrBenefic">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="2"/>
     *                                   &lt;maxLength value="20"/>
     *                                   &lt;whiteSpace value="preserve"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="dtFimBenef">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="mtvFim">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *                                   &lt;pattern value="\d{1,2}"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ideEvento",
        "ideEmpregador",
        "ideBenef",
        "infoBeneficio"
    })
    public static class EvtCdBenPrRP {

        @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
        protected TIdeEveTrab ideEvento;
        @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
        protected TEmprPJ ideEmpregador;
        @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
        protected ESocial.EvtCdBenPrRP.IdeBenef ideBenef;
        @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
        protected ESocial.EvtCdBenPrRP.InfoBeneficio infoBeneficio;
        @XmlAttribute(name = "Id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the ideEvento property.
         * 
         * @return
         *     possible object is
         *     {@link TIdeEveTrab }
         *     
         */
        public TIdeEveTrab getIdeEvento() {
            return ideEvento;
        }

        /**
         * Sets the value of the ideEvento property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIdeEveTrab }
         *     
         */
        public void setIdeEvento(TIdeEveTrab value) {
            this.ideEvento = value;
        }

        /**
         * Gets the value of the ideEmpregador property.
         * 
         * @return
         *     possible object is
         *     {@link TEmprPJ }
         *     
         */
        public TEmprPJ getIdeEmpregador() {
            return ideEmpregador;
        }

        /**
         * Sets the value of the ideEmpregador property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmprPJ }
         *     
         */
        public void setIdeEmpregador(TEmprPJ value) {
            this.ideEmpregador = value;
        }

        /**
         * Gets the value of the ideBenef property.
         * 
         * @return
         *     possible object is
         *     {@link ESocial.EvtCdBenPrRP.IdeBenef }
         *     
         */
        public ESocial.EvtCdBenPrRP.IdeBenef getIdeBenef() {
            return ideBenef;
        }

        /**
         * Sets the value of the ideBenef property.
         * 
         * @param value
         *     allowed object is
         *     {@link ESocial.EvtCdBenPrRP.IdeBenef }
         *     
         */
        public void setIdeBenef(ESocial.EvtCdBenPrRP.IdeBenef value) {
            this.ideBenef = value;
        }

        /**
         * Gets the value of the infoBeneficio property.
         * 
         * @return
         *     possible object is
         *     {@link ESocial.EvtCdBenPrRP.InfoBeneficio }
         *     
         */
        public ESocial.EvtCdBenPrRP.InfoBeneficio getInfoBeneficio() {
            return infoBeneficio;
        }

        /**
         * Sets the value of the infoBeneficio property.
         * 
         * @param value
         *     allowed object is
         *     {@link ESocial.EvtCdBenPrRP.InfoBeneficio }
         *     
         */
        public void setInfoBeneficio(ESocial.EvtCdBenPrRP.InfoBeneficio value) {
            this.infoBeneficio = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cpfBenef">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="\d{11}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="nmBenefic">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="2"/>
         *               &lt;maxLength value="70"/>
         *               &lt;whiteSpace value="preserve"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="dadosBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBenef"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cpfBenef",
            "nmBenefic",
            "dadosBenef"
        })
        public static class IdeBenef {

            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
            protected String cpfBenef;
            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
            protected String nmBenefic;
            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
            protected TDadosBenef dadosBenef;

            /**
             * Gets the value of the cpfBenef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCpfBenef() {
                return cpfBenef;
            }

            /**
             * Sets the value of the cpfBenef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCpfBenef(String value) {
                this.cpfBenef = value;
            }

            /**
             * Gets the value of the nmBenefic property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNmBenefic() {
                return nmBenefic;
            }

            /**
             * Sets the value of the nmBenefic property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNmBenefic(String value) {
                this.nmBenefic = value;
            }

            /**
             * Gets the value of the dadosBenef property.
             * 
             * @return
             *     possible object is
             *     {@link TDadosBenef }
             *     
             */
            public TDadosBenef getDadosBenef() {
                return dadosBenef;
            }

            /**
             * Sets the value of the dadosBenef property.
             * 
             * @param value
             *     allowed object is
             *     {@link TDadosBenef }
             *     
             */
            public void setDadosBenef(TDadosBenef value) {
                this.dadosBenef = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tpPlanRP">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
         *               &lt;pattern value="\d"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="iniBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
         *         &lt;element name="altBeneficio" type="{http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00}TDadosBeneficio" minOccurs="0"/>
         *         &lt;element name="fimBeneficio" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="tpBenef">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
         *                         &lt;pattern value="\d{1,2}"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="nrBenefic">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="2"/>
         *                         &lt;maxLength value="20"/>
         *                         &lt;whiteSpace value="preserve"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="dtFimBenef">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="mtvFim">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
         *                         &lt;pattern value="\d{1,2}"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tpPlanRP",
            "iniBeneficio",
            "altBeneficio",
            "fimBeneficio"
        })
        public static class InfoBeneficio {

            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
            protected byte tpPlanRP;
            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
            protected TDadosBeneficio iniBeneficio;
            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
            protected TDadosBeneficio altBeneficio;
            @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
            protected ESocial.EvtCdBenPrRP.InfoBeneficio.FimBeneficio fimBeneficio;

            /**
             * Gets the value of the tpPlanRP property.
             * 
             */
            public byte getTpPlanRP() {
                return tpPlanRP;
            }

            /**
             * Sets the value of the tpPlanRP property.
             * 
             */
            public void setTpPlanRP(byte value) {
                this.tpPlanRP = value;
            }

            /**
             * Gets the value of the iniBeneficio property.
             * 
             * @return
             *     possible object is
             *     {@link TDadosBeneficio }
             *     
             */
            public TDadosBeneficio getIniBeneficio() {
                return iniBeneficio;
            }

            /**
             * Sets the value of the iniBeneficio property.
             * 
             * @param value
             *     allowed object is
             *     {@link TDadosBeneficio }
             *     
             */
            public void setIniBeneficio(TDadosBeneficio value) {
                this.iniBeneficio = value;
            }

            /**
             * Gets the value of the altBeneficio property.
             * 
             * @return
             *     possible object is
             *     {@link TDadosBeneficio }
             *     
             */
            public TDadosBeneficio getAltBeneficio() {
                return altBeneficio;
            }

            /**
             * Sets the value of the altBeneficio property.
             * 
             * @param value
             *     allowed object is
             *     {@link TDadosBeneficio }
             *     
             */
            public void setAltBeneficio(TDadosBeneficio value) {
                this.altBeneficio = value;
            }

            /**
             * Gets the value of the fimBeneficio property.
             * 
             * @return
             *     possible object is
             *     {@link ESocial.EvtCdBenPrRP.InfoBeneficio.FimBeneficio }
             *     
             */
            public ESocial.EvtCdBenPrRP.InfoBeneficio.FimBeneficio getFimBeneficio() {
                return fimBeneficio;
            }

            /**
             * Sets the value of the fimBeneficio property.
             * 
             * @param value
             *     allowed object is
             *     {@link ESocial.EvtCdBenPrRP.InfoBeneficio.FimBeneficio }
             *     
             */
            public void setFimBeneficio(ESocial.EvtCdBenPrRP.InfoBeneficio.FimBeneficio value) {
                this.fimBeneficio = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="tpBenef">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
             *               &lt;pattern value="\d{1,2}"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="nrBenefic">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="2"/>
             *               &lt;maxLength value="20"/>
             *               &lt;whiteSpace value="preserve"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="dtFimBenef">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="mtvFim">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
             *               &lt;pattern value="\d{1,2}"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tpBenef",
                "nrBenefic",
                "dtFimBenef",
                "mtvFim"
            })
            public static class FimBeneficio {

                @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
                protected byte tpBenef;
                @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
                protected String nrBenefic;
                @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00", required = true)
                protected XMLGregorianCalendar dtFimBenef;
                @XmlElement(namespace = "http://www.esocial.gov.br/schema/evt/evtCdBenPrRP/v02_05_00")
                protected byte mtvFim;

                /**
                 * Gets the value of the tpBenef property.
                 * 
                 */
                public byte getTpBenef() {
                    return tpBenef;
                }

                /**
                 * Sets the value of the tpBenef property.
                 * 
                 */
                public void setTpBenef(byte value) {
                    this.tpBenef = value;
                }

                /**
                 * Gets the value of the nrBenefic property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNrBenefic() {
                    return nrBenefic;
                }

                /**
                 * Sets the value of the nrBenefic property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNrBenefic(String value) {
                    this.nrBenefic = value;
                }

                /**
                 * Gets the value of the dtFimBenef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDtFimBenef() {
                    return dtFimBenef;
                }

                /**
                 * Sets the value of the dtFimBenef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDtFimBenef(XMLGregorianCalendar value) {
                    this.dtFimBenef = value;
                }

                /**
                 * Gets the value of the mtvFim property.
                 * 
                 */
                public byte getMtvFim() {
                    return mtvFim;
                }

                /**
                 * Sets the value of the mtvFim property.
                 * 
                 */
                public void setMtvFim(byte value) {
                    this.mtvFim = value;
                }

            }

        }

    }

}
