//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.03 at 06:57:30 PM BRT 
//


package br.jus.tst.esocial.esquemas.eventos.deslig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_ideEstabLot_infoPerAnt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_ideEstabLot_infoPerAnt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tpInsc" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}TS_tpInsc_EstabLot"/>
 *         &lt;element name="nrInsc" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}TS_nrInsc_EstabLot"/>
 *         &lt;element name="codLotacao" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}TS_codLotacao"/>
 *         &lt;element name="detVerbas" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}T_detVerbas" maxOccurs="200"/>
 *         &lt;element name="infoAgNocivo" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}T_infoAgNocivo" minOccurs="0"/>
 *         &lt;element name="infoSimples" type="{http://www.esocial.gov.br/schema/evt/evtDeslig/v_S_01_03_00}T_infoSimples" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_ideEstabLot_infoPerAnt", propOrder = {
    "tpInsc",
    "nrInsc",
    "codLotacao",
    "detVerbas",
    "infoAgNocivo",
    "infoSimples"
})
public class TIdeEstabLotInfoPerAnt {

    protected byte tpInsc;
    @XmlElement(required = true)
    protected String nrInsc;
    @XmlElement(required = true)
    protected String codLotacao;
    @XmlElement(required = true)
    protected List<TDetVerbas> detVerbas;
    protected TInfoAgNocivo infoAgNocivo;
    protected TInfoSimples infoSimples;

    /**
     * Gets the value of the tpInsc property.
     * 
     */
    public byte getTpInsc() {
        return tpInsc;
    }

    /**
     * Sets the value of the tpInsc property.
     * 
     */
    public void setTpInsc(byte value) {
        this.tpInsc = value;
    }

    /**
     * Gets the value of the nrInsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrInsc() {
        return nrInsc;
    }

    /**
     * Sets the value of the nrInsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrInsc(String value) {
        this.nrInsc = value;
    }

    /**
     * Gets the value of the codLotacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodLotacao() {
        return codLotacao;
    }

    /**
     * Sets the value of the codLotacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodLotacao(String value) {
        this.codLotacao = value;
    }

    /**
     * Gets the value of the detVerbas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detVerbas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetVerbas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDetVerbas }
     * 
     * 
     */
    public List<TDetVerbas> getDetVerbas() {
        if (detVerbas == null) {
            detVerbas = new ArrayList<TDetVerbas>();
        }
        return this.detVerbas;
    }

    /**
     * Gets the value of the infoAgNocivo property.
     * 
     * @return
     *     possible object is
     *     {@link TInfoAgNocivo }
     *     
     */
    public TInfoAgNocivo getInfoAgNocivo() {
        return infoAgNocivo;
    }

    /**
     * Sets the value of the infoAgNocivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInfoAgNocivo }
     *     
     */
    public void setInfoAgNocivo(TInfoAgNocivo value) {
        this.infoAgNocivo = value;
    }

    /**
     * Gets the value of the infoSimples property.
     * 
     * @return
     *     possible object is
     *     {@link TInfoSimples }
     *     
     */
    public TInfoSimples getInfoSimples() {
        return infoSimples;
    }

    /**
     * Sets the value of the infoSimples property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInfoSimples }
     *     
     */
    public void setInfoSimples(TInfoSimples value) {
        this.infoSimples = value;
    }

}
