//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.02 at 02:44:47 PM BRT 
//


package br.jus.tst.esocial.esquemas.eventos.cdbenefalt;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evtCdBenefAlt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_ideEvento_trab_PJ"/>
 *                   &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_ideEmpregador_cnpj"/>
 *                   &lt;element name="ideBenef">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cpfBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpf"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="alteracao">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dtAlteracao" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="dadosBenef">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nmBenefic" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmBenefic"/>
 *                                       &lt;element name="sexo" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
 *                                       &lt;element name="racaCor" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_racaCorBenef"/>
 *                                       &lt;element name="estCiv" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_estCivilBenef" minOccurs="0"/>
 *                                       &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMen"/>
 *                                       &lt;element name="endereco">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;choice>
 *                                                   &lt;element name="brasil" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_brasil"/>
 *                                                   &lt;element name="exterior" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_exterior"/>
 *                                                 &lt;/choice>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="dependente" maxOccurs="99" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="tpDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_tpDep"/>
 *                                                 &lt;element name="nmDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmDep"/>
 *                                                 &lt;element name="dtNascto" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_dtNascto"/>
 *                                                 &lt;element name="cpfDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpfDepBenef" minOccurs="0"/>
 *                                                 &lt;element name="sexoDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
 *                                                 &lt;element name="depIRRF" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_depIRRF_Benef"/>
 *                                                 &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMenDep"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Id" use="required" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_Id" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "evtCdBenefAlt",
    "signature"
})
@XmlRootElement(name = "eSocial")
public class ESocial {

    @XmlElement(required = true)
    protected ESocial.EvtCdBenefAlt evtCdBenefAlt;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the evtCdBenefAlt property.
     * 
     * @return
     *     possible object is
     *     {@link ESocial.EvtCdBenefAlt }
     *     
     */
    public ESocial.EvtCdBenefAlt getEvtCdBenefAlt() {
        return evtCdBenefAlt;
    }

    /**
     * Sets the value of the evtCdBenefAlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESocial.EvtCdBenefAlt }
     *     
     */
    public void setEvtCdBenefAlt(ESocial.EvtCdBenefAlt value) {
        this.evtCdBenefAlt = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ideEvento" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_ideEvento_trab_PJ"/>
     *         &lt;element name="ideEmpregador" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_ideEmpregador_cnpj"/>
     *         &lt;element name="ideBenef">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cpfBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpf"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="alteracao">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dtAlteracao" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="dadosBenef">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="nmBenefic" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmBenefic"/>
     *                             &lt;element name="sexo" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
     *                             &lt;element name="racaCor" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_racaCorBenef"/>
     *                             &lt;element name="estCiv" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_estCivilBenef" minOccurs="0"/>
     *                             &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMen"/>
     *                             &lt;element name="endereco">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;choice>
     *                                         &lt;element name="brasil" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_brasil"/>
     *                                         &lt;element name="exterior" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_exterior"/>
     *                                       &lt;/choice>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="dependente" maxOccurs="99" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="tpDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_tpDep"/>
     *                                       &lt;element name="nmDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmDep"/>
     *                                       &lt;element name="dtNascto" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_dtNascto"/>
     *                                       &lt;element name="cpfDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpfDepBenef" minOccurs="0"/>
     *                                       &lt;element name="sexoDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
     *                                       &lt;element name="depIRRF" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_depIRRF_Benef"/>
     *                                       &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMenDep"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Id" use="required" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_Id" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ideEvento",
        "ideEmpregador",
        "ideBenef",
        "alteracao"
    })
    public static class EvtCdBenefAlt {

        @XmlElement(required = true)
        protected TIdeEventoTrabPJ ideEvento;
        @XmlElement(required = true)
        protected TIdeEmpregadorCnpj ideEmpregador;
        @XmlElement(required = true)
        protected ESocial.EvtCdBenefAlt.IdeBenef ideBenef;
        @XmlElement(required = true)
        protected ESocial.EvtCdBenefAlt.Alteracao alteracao;
        @XmlAttribute(name = "Id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String id;

        /**
         * Gets the value of the ideEvento property.
         * 
         * @return
         *     possible object is
         *     {@link TIdeEventoTrabPJ }
         *     
         */
        public TIdeEventoTrabPJ getIdeEvento() {
            return ideEvento;
        }

        /**
         * Sets the value of the ideEvento property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIdeEventoTrabPJ }
         *     
         */
        public void setIdeEvento(TIdeEventoTrabPJ value) {
            this.ideEvento = value;
        }

        /**
         * Gets the value of the ideEmpregador property.
         * 
         * @return
         *     possible object is
         *     {@link TIdeEmpregadorCnpj }
         *     
         */
        public TIdeEmpregadorCnpj getIdeEmpregador() {
            return ideEmpregador;
        }

        /**
         * Sets the value of the ideEmpregador property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIdeEmpregadorCnpj }
         *     
         */
        public void setIdeEmpregador(TIdeEmpregadorCnpj value) {
            this.ideEmpregador = value;
        }

        /**
         * Gets the value of the ideBenef property.
         * 
         * @return
         *     possible object is
         *     {@link ESocial.EvtCdBenefAlt.IdeBenef }
         *     
         */
        public ESocial.EvtCdBenefAlt.IdeBenef getIdeBenef() {
            return ideBenef;
        }

        /**
         * Sets the value of the ideBenef property.
         * 
         * @param value
         *     allowed object is
         *     {@link ESocial.EvtCdBenefAlt.IdeBenef }
         *     
         */
        public void setIdeBenef(ESocial.EvtCdBenefAlt.IdeBenef value) {
            this.ideBenef = value;
        }

        /**
         * Gets the value of the alteracao property.
         * 
         * @return
         *     possible object is
         *     {@link ESocial.EvtCdBenefAlt.Alteracao }
         *     
         */
        public ESocial.EvtCdBenefAlt.Alteracao getAlteracao() {
            return alteracao;
        }

        /**
         * Sets the value of the alteracao property.
         * 
         * @param value
         *     allowed object is
         *     {@link ESocial.EvtCdBenefAlt.Alteracao }
         *     
         */
        public void setAlteracao(ESocial.EvtCdBenefAlt.Alteracao value) {
            this.alteracao = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dtAlteracao" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="dadosBenef">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="nmBenefic" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmBenefic"/>
         *                   &lt;element name="sexo" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
         *                   &lt;element name="racaCor" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_racaCorBenef"/>
         *                   &lt;element name="estCiv" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_estCivilBenef" minOccurs="0"/>
         *                   &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMen"/>
         *                   &lt;element name="endereco">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;choice>
         *                               &lt;element name="brasil" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_brasil"/>
         *                               &lt;element name="exterior" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_exterior"/>
         *                             &lt;/choice>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="dependente" maxOccurs="99" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="tpDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_tpDep"/>
         *                             &lt;element name="nmDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmDep"/>
         *                             &lt;element name="dtNascto" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_dtNascto"/>
         *                             &lt;element name="cpfDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpfDepBenef" minOccurs="0"/>
         *                             &lt;element name="sexoDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
         *                             &lt;element name="depIRRF" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_depIRRF_Benef"/>
         *                             &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMenDep"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dtAlteracao",
            "dadosBenef"
        })
        public static class Alteracao {

            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dtAlteracao;
            @XmlElement(required = true)
            protected ESocial.EvtCdBenefAlt.Alteracao.DadosBenef dadosBenef;

            /**
             * Gets the value of the dtAlteracao property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDtAlteracao() {
                return dtAlteracao;
            }

            /**
             * Sets the value of the dtAlteracao property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDtAlteracao(XMLGregorianCalendar value) {
                this.dtAlteracao = value;
            }

            /**
             * Gets the value of the dadosBenef property.
             * 
             * @return
             *     possible object is
             *     {@link ESocial.EvtCdBenefAlt.Alteracao.DadosBenef }
             *     
             */
            public ESocial.EvtCdBenefAlt.Alteracao.DadosBenef getDadosBenef() {
                return dadosBenef;
            }

            /**
             * Sets the value of the dadosBenef property.
             * 
             * @param value
             *     allowed object is
             *     {@link ESocial.EvtCdBenefAlt.Alteracao.DadosBenef }
             *     
             */
            public void setDadosBenef(ESocial.EvtCdBenefAlt.Alteracao.DadosBenef value) {
                this.dadosBenef = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="nmBenefic" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmBenefic"/>
             *         &lt;element name="sexo" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
             *         &lt;element name="racaCor" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_racaCorBenef"/>
             *         &lt;element name="estCiv" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_estCivilBenef" minOccurs="0"/>
             *         &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMen"/>
             *         &lt;element name="endereco">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;choice>
             *                     &lt;element name="brasil" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_brasil"/>
             *                     &lt;element name="exterior" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_exterior"/>
             *                   &lt;/choice>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="dependente" maxOccurs="99" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="tpDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_tpDep"/>
             *                   &lt;element name="nmDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmDep"/>
             *                   &lt;element name="dtNascto" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_dtNascto"/>
             *                   &lt;element name="cpfDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpfDepBenef" minOccurs="0"/>
             *                   &lt;element name="sexoDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
             *                   &lt;element name="depIRRF" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_depIRRF_Benef"/>
             *                   &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMenDep"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nmBenefic",
                "sexo",
                "racaCor",
                "estCiv",
                "incFisMen",
                "endereco",
                "dependente"
            })
            public static class DadosBenef {

                @XmlElement(required = true)
                protected String nmBenefic;
                @XmlElement(required = true)
                @XmlSchemaType(name = "string")
                protected TSSexo sexo;
                protected byte racaCor;
                protected Byte estCiv;
                @XmlElement(required = true)
                @XmlSchemaType(name = "string")
                protected TSSimNao incFisMen;
                @XmlElement(required = true)
                protected ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Endereco endereco;
                protected List<ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Dependente> dependente;

                /**
                 * Gets the value of the nmBenefic property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNmBenefic() {
                    return nmBenefic;
                }

                /**
                 * Sets the value of the nmBenefic property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNmBenefic(String value) {
                    this.nmBenefic = value;
                }

                /**
                 * Gets the value of the sexo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TSSexo }
                 *     
                 */
                public TSSexo getSexo() {
                    return sexo;
                }

                /**
                 * Sets the value of the sexo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TSSexo }
                 *     
                 */
                public void setSexo(TSSexo value) {
                    this.sexo = value;
                }

                /**
                 * Gets the value of the racaCor property.
                 * 
                 */
                public byte getRacaCor() {
                    return racaCor;
                }

                /**
                 * Sets the value of the racaCor property.
                 * 
                 */
                public void setRacaCor(byte value) {
                    this.racaCor = value;
                }

                /**
                 * Gets the value of the estCiv property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getEstCiv() {
                    return estCiv;
                }

                /**
                 * Sets the value of the estCiv property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setEstCiv(Byte value) {
                    this.estCiv = value;
                }

                /**
                 * Gets the value of the incFisMen property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TSSimNao }
                 *     
                 */
                public TSSimNao getIncFisMen() {
                    return incFisMen;
                }

                /**
                 * Sets the value of the incFisMen property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TSSimNao }
                 *     
                 */
                public void setIncFisMen(TSSimNao value) {
                    this.incFisMen = value;
                }

                /**
                 * Gets the value of the endereco property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Endereco }
                 *     
                 */
                public ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Endereco getEndereco() {
                    return endereco;
                }

                /**
                 * Sets the value of the endereco property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Endereco }
                 *     
                 */
                public void setEndereco(ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Endereco value) {
                    this.endereco = value;
                }

                /**
                 * Gets the value of the dependente property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dependente property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDependente().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Dependente }
                 * 
                 * 
                 */
                public List<ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Dependente> getDependente() {
                    if (dependente == null) {
                        dependente = new ArrayList<ESocial.EvtCdBenefAlt.Alteracao.DadosBenef.Dependente>();
                    }
                    return this.dependente;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="tpDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_tpDep"/>
                 *         &lt;element name="nmDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_nmDep"/>
                 *         &lt;element name="dtNascto" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_dtNascto"/>
                 *         &lt;element name="cpfDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpfDepBenef" minOccurs="0"/>
                 *         &lt;element name="sexoDep" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_sexo"/>
                 *         &lt;element name="depIRRF" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_depIRRF_Benef"/>
                 *         &lt;element name="incFisMen" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_incFisMenDep"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "tpDep",
                    "nmDep",
                    "dtNascto",
                    "cpfDep",
                    "sexoDep",
                    "depIRRF",
                    "incFisMen"
                })
                public static class Dependente {

                    @XmlElement(required = true)
                    protected String tpDep;
                    @XmlElement(required = true)
                    protected String nmDep;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "date")
                    protected XMLGregorianCalendar dtNascto;
                    protected String cpfDep;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "string")
                    protected TSSexo sexoDep;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "string")
                    protected TSSimNao depIRRF;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "string")
                    protected TSSimNao incFisMen;

                    /**
                     * Gets the value of the tpDep property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTpDep() {
                        return tpDep;
                    }

                    /**
                     * Sets the value of the tpDep property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTpDep(String value) {
                        this.tpDep = value;
                    }

                    /**
                     * Gets the value of the nmDep property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNmDep() {
                        return nmDep;
                    }

                    /**
                     * Sets the value of the nmDep property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNmDep(String value) {
                        this.nmDep = value;
                    }

                    /**
                     * Gets the value of the dtNascto property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getDtNascto() {
                        return dtNascto;
                    }

                    /**
                     * Sets the value of the dtNascto property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setDtNascto(XMLGregorianCalendar value) {
                        this.dtNascto = value;
                    }

                    /**
                     * Gets the value of the cpfDep property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCpfDep() {
                        return cpfDep;
                    }

                    /**
                     * Sets the value of the cpfDep property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCpfDep(String value) {
                        this.cpfDep = value;
                    }

                    /**
                     * Gets the value of the sexoDep property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TSSexo }
                     *     
                     */
                    public TSSexo getSexoDep() {
                        return sexoDep;
                    }

                    /**
                     * Sets the value of the sexoDep property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TSSexo }
                     *     
                     */
                    public void setSexoDep(TSSexo value) {
                        this.sexoDep = value;
                    }

                    /**
                     * Gets the value of the depIRRF property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TSSimNao }
                     *     
                     */
                    public TSSimNao getDepIRRF() {
                        return depIRRF;
                    }

                    /**
                     * Sets the value of the depIRRF property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TSSimNao }
                     *     
                     */
                    public void setDepIRRF(TSSimNao value) {
                        this.depIRRF = value;
                    }

                    /**
                     * Gets the value of the incFisMen property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TSSimNao }
                     *     
                     */
                    public TSSimNao getIncFisMen() {
                        return incFisMen;
                    }

                    /**
                     * Sets the value of the incFisMen property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TSSimNao }
                     *     
                     */
                    public void setIncFisMen(TSSimNao value) {
                        this.incFisMen = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;choice>
                 *           &lt;element name="brasil" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_brasil"/>
                 *           &lt;element name="exterior" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}T_endereco_exterior"/>
                 *         &lt;/choice>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "brasil",
                    "exterior"
                })
                public static class Endereco {

                    protected TEnderecoBrasil brasil;
                    protected TEnderecoExterior exterior;

                    /**
                     * Gets the value of the brasil property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEnderecoBrasil }
                     *     
                     */
                    public TEnderecoBrasil getBrasil() {
                        return brasil;
                    }

                    /**
                     * Sets the value of the brasil property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEnderecoBrasil }
                     *     
                     */
                    public void setBrasil(TEnderecoBrasil value) {
                        this.brasil = value;
                    }

                    /**
                     * Gets the value of the exterior property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEnderecoExterior }
                     *     
                     */
                    public TEnderecoExterior getExterior() {
                        return exterior;
                    }

                    /**
                     * Sets the value of the exterior property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEnderecoExterior }
                     *     
                     */
                    public void setExterior(TEnderecoExterior value) {
                        this.exterior = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cpfBenef" type="{http://www.esocial.gov.br/schema/evt/evtCdBenefAlt/v_S_01_01_00}TS_cpf"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cpfBenef"
        })
        public static class IdeBenef {

            @XmlElement(required = true)
            protected String cpfBenef;

            /**
             * Gets the value of the cpfBenef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCpfBenef() {
                return cpfBenef;
            }

            /**
             * Sets the value of the cpfBenef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCpfBenef(String value) {
                this.cpfBenef = value;
            }

        }

    }

}
