//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.01 at 05:32:53 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esocial.gov.br/servicos/empregador/consulta/identificadores-eventos/v1_0_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.jus.tst.esocialjt.comunicacao.wsdl;
