#!/bin/bash
mvn install -DskipTests -B
docker build -t tstlabs/esocial-jt-service .
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push tstlabs/esocial-jt-service