################################################################
#  Esocial-JT (oficial)
################################################################
backend:
  name: esocialjt-backend
  # image: registry-gitlab.tjdft.jus.br/cosoft/nusof5/esocial/esocial-jt/backend
  image: tstlabs/esocial-jt-service:latest
  replicas: 1
  port: 8080
  protocol: TCP
  usuario: 1000
  grupo: 1000
  env: 
    ESOCIALJT_AMBIENTE: PRODUCAO_RESTRITA
    ESOCIALJT_ARQUIVOCERTIFICADO: /config/esocial.pfx
    JAVA_OPTS: '-Xms512m -Xmx2g'
    KEYCLOAK_AUTH_SERVER_URL: 'https://sso.apps.tjdft.jus.br/auth'
    KEYCLOAK_BEARER_ONLY: 'true'
    KEYCLOAK_CONFIDENTIAL_PORT: '0'
    KEYCLOAK_ENABLED: 'true'
    KEYCLOAK_REALM: SUDES
    KEYCLOAK_RESOURCE: esocialjt-backend
    KEYCLOAK_SSL_REQUIRED: external
    LOGGING_LEVEL_ORG_HIBERNATE: ERROR
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
    LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE: 10MB
    LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY: '7'
    LOGGING_LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP: 100MB
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: 'metrics, info, health, esocialhealth'
    MANAGEMENT_ENDPOINT_HEALTH_ENABLED: 'true'
    MANAGEMENT_ENDPOINT_METRICS_ENABLED: 'true'
    SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: '50000'
    SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: '300000'
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: '20'
    SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: '900000'
    SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: '10'    
    SPRING_DATASOURCE_USERNAME: esocial
    SPRING_FLYWAY_BASELINE_ON_MIGRATE: 'true'
    SPRING_SECURITY_CSRF_ENABLED: 'false'
    SPRING_WEBFLUX_CORS_ENABLED: 'false'
    TZ: America/Sao_Paulo
frontend:
  name: esocialjt-frontend
  # image: registry-gitlab.tjdft.jus.br/cosoft/nusof5/esocial/esocial-jt/frontend
  image: tstlabs/esocial-jt-frontend:latest
  replicas: 1
  port: 8080
  protocol: TCP
  usuario: 1000
  grupo: 1000
  env:
    FRONTEND_ENV_ESOCIAL_JT_SERVICE_URL: 'https://esocial-jt-api.apps.tjdft.jus.br/esocial-jt-service/'
    FRONTEND_ENV_HABILITA_CABECALHO: S
    FRONTEND_ENV_KEYCLOAK_CLIENT_ID: esocialjt-frontend
    FRONTEND_ENV_KEYCLOAK_REALM: SUDES
    FRONTEND_ENV_KEYCLOAK_URL: 'https://sso.apps.tjdft.jus.br/auth'    
    FRONTEND_ENV_PRIMARY_COLOR: '#0067A0'
    FRONTEND_ENV_PRODUCAO_RESTRITA: S
    FRONTEND_ENV_SECONDARY_COLOR: '#19857b'